-- Migration 024: NEUTRALIZED — superseded by 025_shared_ledger_snapshots.sql.
--
-- This migration originally tried to create the WhatsApp "see the full ledger"
-- snapshot store as:
--     CREATE TABLE IF NOT EXISTS shared_ledgers (token, payload, expires_at);
--     CREATE INDEX  IF NOT EXISTS idx_shared_ledgers_expires ON shared_ledgers (expires_at);
-- but a table literally named `shared_ledgers` ALREADY EXISTS from migration 021
-- (a different, two-party-tab schema with no `expires_at` column). So:
--   * the CREATE TABLE IF NOT EXISTS was a no-op against 021's table, and
--   * the CREATE INDEX on the non-existent `expires_at` column HARD-ERRORED
--     ('column "expires_at" does not exist').
-- db.Migrate() runs each file's whole body in one transaction (see db.go), so the
-- error rolled the transaction back: 024 was NEVER recorded as applied on ANY
-- database, and worse, it aborted the entire migration chain at boot.
--
-- Because 024 never successfully applied anywhere, rewriting its body (rather than
-- adding yet another migration) does NOT violate the append-only rule — that rule
-- protects migrations already recorded in schema_migrations, and this one isn't.
-- The body is now an intentional no-op so the chain can progress to 025, which
-- creates the snapshot table under a non-colliding name (`shared_ledger_snapshots`).
SELECT 1;
