package expo.modules.kaatabtclassic

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.ServiceCompat

/**
 * Native START_STICKY foreground service for kaata "Nearby sync" — the Briar
 * BriarService model.
 *
 * WHY THIS EXISTS (replaces notifee's foreground service):
 *   notifee's foreground service is bound to a JS HeadlessJS callback — it only
 *   stays alive while the React bundle is loaded. When MIUI kills the process on
 *   swipe-away, the notification vanishes; and the OS's restart-before-JS path
 *   trips the 5s ForegroundServiceDidNotStartInTimeException. This service has
 *   ZERO JS dependency: it builds its own channel + notification and calls
 *   startForeground() synchronously in onStartCommand, so it survives process
 *   death and a sticky restart (null intent) re-posts the notification from
 *   persisted state without any JS running.
 *
 * CONTRACT (do not break):
 *   - onStartCommand MUST call startForeground() within ~5s on EVERY invocation
 *     — including a STOP command and a null-intent sticky restart — or Android
 *     force-kills the process. So we ALWAYS post the notification first.
 *   - The channel id MUST equal foreground.ts SHOP_MODE_CHANNEL_ID ("shop-mode")
 *     so we don't post to a missing channel (silent drop -> 5s crash).
 *   - smallIcon MUST resolve to a real drawable (a 0 icon crashes
 *     startForeground); "notification_icon" is generated by expo-notifications.
 *   - foregroundServiceType MUST match the manifest declaration
 *     (connectedDevice|dataSync) on API 34+ or startForeground throws.
 */
class KaataForegroundService : Service() {

  companion object {
    private const val TAG = "KaataFgs"

    // MUST match foreground.ts SHOP_MODE_CHANNEL_ID.
    const val CHANNEL_ID = "shop-mode"

    // Arbitrary stable non-zero notification id.
    const val NOTIF_ID = 0x6B61

    const val ACTION_START = "expo.modules.kaatabtclassic.FGS_START"
    const val ACTION_STOP = "expo.modules.kaatabtclassic.FGS_STOP"

    const val EXTRA_TITLE = "title"
    const val EXTRA_BODY = "body"
    const val EXTRA_CHANNEL_NAME = "channelName"
    const val EXTRA_CHANNEL_DESC = "channelDesc"

    private const val PREFS = "kaata_fgs_prefs"
    private const val KEY_TITLE = "title"
    private const val KEY_BODY = "body"
    private const val KEY_CHANNEL_NAME = "channelName"
    private const val KEY_CHANNEL_DESC = "channelDesc"

    // Safe English fallbacks for the no-JS sticky-restart case. In practice the
    // channel already exists (created by JS on a prior launch) and persisted
    // title/body are present, so these are last-resort defaults only.
    private const val DEFAULT_TITLE = "Nearby sync is on"
    private const val DEFAULT_BODY = "Tap to open Kaata"
    private const val DEFAULT_CHANNEL_NAME = "Nearby sync"
  }

  override fun onBind(intent: Intent?): IBinder? = null

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    val prefs = getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    if (intent?.action == ACTION_STOP) {
      // Satisfy the 5s rule defensively even on a stop command, then tear down.
      startForegroundSafely(buildNotification(prefs, intent))
      stopForegroundCompat()
      stopSelf()
      return START_NOT_STICKY
    }

    // START / UPDATE / sticky-restart(null). Persist the latest copy so a
    // sticky restart (null intent, no JS yet) can rebuild the notification.
    if (intent != null) {
      val edit = prefs.edit()
      intent.getStringExtra(EXTRA_TITLE)?.let { edit.putString(KEY_TITLE, it) }
      intent.getStringExtra(EXTRA_BODY)?.let { edit.putString(KEY_BODY, it) }
      intent.getStringExtra(EXTRA_CHANNEL_NAME)?.let { edit.putString(KEY_CHANNEL_NAME, it) }
      intent.getStringExtra(EXTRA_CHANNEL_DESC)?.let { edit.putString(KEY_CHANNEL_DESC, it) }
      edit.apply()
    }

    val entered = startForegroundSafely(buildNotification(prefs, intent))
    if (!entered) {
      // Couldn't enter the foreground — e.g. an OS-initiated restart that landed
      // in an API 31+ background-start block, or a transient channel failure.
      // Do NOT return START_STICKY here: that would loop a never-foregrounded
      // service the OS keeps re-killing. Stop cleanly; MeshController's JS
      // auto-resume restarts us properly next time the app is foregrounded.
      stopSelf()
      return START_NOT_STICKY
    }

    // START_STICKY: if the OS kills us under memory pressure, recreate the
    // service (null intent) and we re-post the notification from prefs. The
    // mesh itself resumes in JS via MeshController's auto-resume when the user
    // next foregrounds the app (kaata's mesh runs in JS, not native).
    return START_STICKY
  }

  override fun onDestroy() {
    stopForegroundCompat()
    super.onDestroy()
  }

  /** Returns true iff the service successfully entered the foreground. */
  private fun startForegroundSafely(notification: Notification): Boolean {
    return try {
      val type =
        ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC or
          ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE
      ServiceCompat.startForeground(this, NOTIF_ID, notification, type)
      true
    } catch (e: Throwable) {
      // Never let startForeground throw out of onStartCommand (it can throw
      // ForegroundServiceStartNotAllowedException synchronously on API 31+).
      // The caller decides whether to stop; see onStartCommand.
      Log.w(TAG, "startForeground failed", e)
      false
    }
  }

  private fun stopForegroundCompat() {
    try {
      ServiceCompat.stopForeground(this, ServiceCompat.STOP_FOREGROUND_REMOVE)
    } catch (e: Throwable) {
      Log.w(TAG, "stopForeground failed", e)
    }
  }

  private fun buildNotification(prefs: SharedPreferences, intent: Intent?): Notification {
    ensureChannel(prefs)

    val title =
      intent?.getStringExtra(EXTRA_TITLE) ?: prefs.getString(KEY_TITLE, null) ?: DEFAULT_TITLE
    val body =
      intent?.getStringExtra(EXTRA_BODY) ?: prefs.getString(KEY_BODY, null) ?: DEFAULT_BODY

    val launch = packageManager.getLaunchIntentForPackage(packageName)?.apply {
      addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
    }
    val contentPi: PendingIntent? =
      if (launch != null) {
        var flags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          flags = flags or PendingIntent.FLAG_IMMUTABLE
        }
        PendingIntent.getActivity(this, 0, launch, flags)
      } else {
        null
      }

    val builder = NotificationCompat.Builder(this, CHANNEL_ID)
      .setContentTitle(title)
      .setContentText(body)
      .setSmallIcon(resolveSmallIcon())
      .setOngoing(true)
      .setPriority(NotificationCompat.PRIORITY_LOW)
      .setVisibility(NotificationCompat.VISIBILITY_SECRET)
      .setShowWhen(false)
    if (contentPi != null) builder.setContentIntent(contentPi)
    return builder.build()
  }

  private fun ensureChannel(prefs: SharedPreferences) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
    val nm = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    // Don't clobber an existing channel — its name/description may already have
    // been set (localized) by the JS layer, and importance is user-controlled
    // after creation anyway.
    if (nm.getNotificationChannel(CHANNEL_ID) != null) return
    val name = prefs.getString(KEY_CHANNEL_NAME, null) ?: DEFAULT_CHANNEL_NAME
    val desc = prefs.getString(KEY_CHANNEL_DESC, null) ?: ""
    val channel = NotificationChannel(CHANNEL_ID, name, NotificationManager.IMPORTANCE_LOW).apply {
      description = desc
      enableVibration(false)
      setSound(null, null)
    }
    nm.createNotificationChannel(channel)
  }

  private fun resolveSmallIcon(): Int {
    // expo-notifications generates res/drawable*/notification_icon (see app.json).
    val id = resources.getIdentifier("notification_icon", "drawable", packageName)
    if (id != 0) return id
    // Fallbacks so startForeground never receives a 0 icon (which crashes).
    val appIcon = applicationInfo.icon
    if (appIcon != 0) return appIcon
    return android.R.drawable.ic_dialog_info
  }
}
