package expo.modules.kaatabtclassic

import android.app.AlarmManager
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.PowerManager
import android.os.SystemClock
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.ServiceCompat
import expo.modules.kaatabtclassic.mesh.MeshEngine

/**
 * Native START_STICKY foreground service for kaata "Nearby sync" — the Briar
 * BriarService model.
 *
 * WHY THIS EXISTS (replaces notifee's foreground service):
 *   notifee's foreground service is bound to a JS HeadlessJS callback — it only
 *   stays alive while the React bundle is loaded. When MIUI kills the process on
 *   swipe-away, the notification vanishes; and the OS's restart-before-JS path
 *   trips the 5s ForegroundServiceDidNotStartInTimeException. This service has
 *   ZERO JS dependency: it builds its own channel + notification and calls
 *   startForeground() synchronously in onStartCommand, so it survives process
 *   death and a sticky restart (null intent) re-posts the notification from
 *   persisted state without any JS running.
 *
 * CONTRACT (do not break):
 *   - onStartCommand MUST call startForeground() within ~5s on EVERY invocation
 *     — including a STOP command and a null-intent sticky restart — or Android
 *     force-kills the process. So we ALWAYS post the notification first.
 *   - The channel id MUST equal foreground.ts SHOP_MODE_CHANNEL_ID ("shop-mode")
 *     so we don't post to a missing channel (silent drop -> 5s crash).
 *   - smallIcon MUST resolve to a real drawable (a 0 icon crashes
 *     startForeground); "notification_icon" is generated by expo-notifications.
 *   - foregroundServiceType MUST match the manifest declaration
 *     (connectedDevice) on API 34+ or startForeground throws.
 */
class KaataForegroundService : Service() {

  companion object {
    private const val TAG = "KaataFgs"

    // MUST match foreground.ts SHOP_MODE_CHANNEL_ID.
    const val CHANNEL_ID = "shop-mode"

    // Arbitrary stable non-zero notification id.
    const val NOTIF_ID = 0x6B61

    const val ACTION_START = "expo.modules.kaatabtclassic.FGS_START"
    const val ACTION_STOP = "expo.modules.kaatabtclassic.FGS_STOP"

    const val EXTRA_TITLE = "title"
    const val EXTRA_BODY = "body"
    const val EXTRA_CHANNEL_NAME = "channelName"
    const val EXTRA_CHANNEL_DESC = "channelDesc"

    // Public so KaataMeshAlarmReceiver can read the should-run flag with a plain
    // Context after a process kill. Same file KaataBgMeshGate uses.
    const val PREFS = "kaata_fgs_prefs"
    private const val KEY_TITLE = "title"
    private const val KEY_BODY = "body"
    private const val KEY_CHANNEL_NAME = "channelName"
    private const val KEY_CHANNEL_DESC = "channelDesc"

    // Set true while the user wants Nearby sync running (ACTION_START), false on
    // ACTION_STOP. The revival alarm reads it (with a plain Context, post-kill) to
    // decide whether to bring the service back.
    const val KEY_FGS_SHOULD_RUN = "fgs_should_run"

    // Doze-exempt revival alarm (port of Briar's AndroidTaskScheduler 15-min
    // setAndAllowWhileIdle backstop). If the OS hard-kills the process despite the
    // FGS + renewable wakelock, this alarm fires, re-grants a temporary
    // FGS-start allowlist, and revives the service. Unlike Briar we DO auto-revive
    // (no DB-key privacy gate). Self-reschedules in the receiver.
    private const val REVIVAL_ALARM_MS = 15 * 60 * 1000L
    private const val REVIVAL_ALARM_REQUEST = 0x6B62

    // Safe English fallbacks for the no-JS sticky-restart case. In practice the
    // channel already exists (created by JS on a prior launch) and persisted
    // title/body are present, so these are last-resort defaults only.
    private const val DEFAULT_TITLE = "Nearby sync is on"
    private const val DEFAULT_BODY = "Tap to open Kaata"
    private const val DEFAULT_CHANNEL_NAME = "Nearby sync"

    // #43 P2: how often this resident FGS spawns a bounded headless mesh window
    // after a swipe-kill. MUST be comfortably > KaataMeshHeadlessService's
    // TASK_TIMEOUT_MS (60s) so windows never overlap (no two headless services).
    // 90s => a killed phone syncs within ~90s of a peer's edit (vs Phase 1's
    // ~15min, vs "never"). First tick is delayed so a normal foreground start
    // (JS alive) doesn't immediately spawn a redundant headless window.
    private const val BG_TICK_MS = 90_000L
    private const val BG_TICK_FIRST_MS = 30_000L

    // Native MeshEngine window length per tick (< the gap to the next tick so a
    // failed/long window can't pile up). 60s of in-process accept/dial per 90s.
    private const val NATIVE_WINDOW_MS = 60_000L

    // Renewable-wakelock cadence (ported from Briar dont-kill-me-lib
    // AndroidWakeLockManagerImpl): rotate the lock every minute, each acquire
    // timed at duration+margin, so an OEM "wake lock held too long" killer
    // (Huawei PowerGenie etc.) never sees a single long-held lock to drop.
    private const val LOCK_DURATION_MS = 60_000L
    private const val SAFETY_MARGIN_MS = 30_000L

    // --- Revival alarm + run-state — callable from the FGS AND the receiver ---

    /** (Re)start the FGS. Safe to call after a process kill — alarm delivery
     *  grants a temporary FGS-start allowlist. Bare ACTION_START; onStartCommand
     *  rebuilds the notification from persisted prefs (no JS needed). */
    fun ensureRunning(ctx: Context) {
      try {
        val i = Intent(ctx, KaataForegroundService::class.java).apply { action = ACTION_START }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) ctx.startForegroundService(i)
        else ctx.startService(i)
      } catch (e: Throwable) {
        Log.w(TAG, "ensureRunning failed", e)
      }
    }

    fun scheduleRevivalAlarm(ctx: Context) {
      try {
        val am = ctx.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        val at = SystemClock.elapsedRealtime() + REVIVAL_ALARM_MS
        val pi = revivalPendingIntent(ctx)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          am.setAndAllowWhileIdle(AlarmManager.ELAPSED_REALTIME_WAKEUP, at, pi)
        } else {
          am.set(AlarmManager.ELAPSED_REALTIME_WAKEUP, at, pi)
        }
      } catch (e: Throwable) {
        Log.w(TAG, "scheduleRevivalAlarm failed", e)
      }
    }

    fun cancelRevivalAlarm(ctx: Context) {
      try {
        val am = ctx.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        am.cancel(revivalPendingIntent(ctx))
      } catch (e: Throwable) {
        Log.w(TAG, "cancelRevivalAlarm failed", e)
      }
    }

    private fun revivalPendingIntent(ctx: Context): PendingIntent {
      val i = Intent(ctx, KaataMeshAlarmReceiver::class.java)
      var flags = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        flags = flags or PendingIntent.FLAG_IMMUTABLE
      }
      return PendingIntent.getBroadcast(ctx, REVIVAL_ALARM_REQUEST, i, flags)
    }
  }

  // RENEWABLE partial wakelock — direct port of Briar's dont-kill-me-lib
  // RenewableWakeLock + AndroidWakeLockManagerImpl. Instead of one long-held lock
  // (which aggressive OEM power managers flag as "held too long" and silently
  // drop, lowering our process priority and making us a soft kill target on
  // swipe), we hold a SHORT timed lock and swap it for a fresh one every
  // LOCK_DURATION_MS — acquiring the new one BEFORE releasing the old (zero gap).
  // The tag is disguised as a system service the known OEM killers whitelist.
  private var wakeLock: PowerManager.WakeLock? = null
  private val wakeHandler = Handler(Looper.getMainLooper())
  private var wakeRenewScheduled = false

  private val renewWakeLock =
    object : Runnable {
      override fun run() {
        try {
          val pm = getSystemService(Context.POWER_SERVICE) as PowerManager
          val fresh =
            pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, wakeLockTag()).apply {
              setReferenceCounted(false)
              acquire(LOCK_DURATION_MS + SAFETY_MARGIN_MS)
            }
          val old = wakeLock
          wakeLock = fresh
          try {
            if (old?.isHeld == true) old.release()
          } catch (e: Throwable) {
            Log.w(TAG, "release old wakelock failed", e)
          }
        } catch (e: Throwable) {
          Log.w(TAG, "renew wakelock failed", e)
        }
        wakeHandler.postDelayed(this, LOCK_DURATION_MS)
      }
    }

  private fun acquireWakeLock() {
    if (wakeRenewScheduled) return
    try {
      val pm = getSystemService(Context.POWER_SERVICE) as PowerManager
      wakeLock =
        pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, wakeLockTag()).apply {
          setReferenceCounted(false)
          // Timed acquire (duration + margin), like Briar — a self-releasing
          // safety net if renew somehow never runs.
          acquire(LOCK_DURATION_MS + SAFETY_MARGIN_MS)
        }
      wakeRenewScheduled = true
      wakeHandler.postDelayed(renewWakeLock, LOCK_DURATION_MS)
    } catch (e: Throwable) {
      Log.w(TAG, "acquireWakeLock failed", e)
    }
  }

  private fun releaseWakeLock() {
    wakeHandler.removeCallbacks(renewWakeLock)
    wakeRenewScheduled = false
    try {
      wakeLock?.let { if (it.isHeld) it.release() }
    } catch (e: Throwable) {
      Log.w(TAG, "releaseWakeLock failed", e)
    }
    wakeLock = null
  }

  /**
   * Disguise the wakelock tag as a system service the known OEM power-managers
   * whitelist, so our lock isn't ignored/killed (port of dont-kill-me-lib
   * AndroidWakeLockManagerImpl.getWakeLockTag): Huawei PowerGenie ->
   * "LocationManagerService"; Evenwell/Asus -> "AudioIn"; else our package name.
   */
  private fun wakeLockTag(): String =
    try {
      val pm = packageManager
      when {
        isInstalled(pm, "com.huawei.powergenie") -> "LocationManagerService"
        isInstalled(pm, "com.evenwell.PowerMonitor") -> "AudioIn"
        else -> packageName
      }
    } catch (e: Throwable) {
      packageName
    }

  private fun isInstalled(pm: android.content.pm.PackageManager, pkg: String): Boolean =
    try {
      pm.getPackageInfo(pkg, 0)
      true
    } catch (e: Throwable) {
      false
    }

  // #43 P2: spawn a bounded headless mesh window on a tick so a SWIPE-KILLED phone
  // keeps syncing (this FGS survives swipe-kill via START_STICKY + stopWithTask
  // false; its Handler keeps ticking). All gating is fail-closed: nothing spawns
  // unless the kill-switch is on AND no foreground JS mesh is alive AND the OEM
  // isn't a known-hostile one.
  private val bgHandler = Handler(Looper.getMainLooper())
  private var bgTickScheduled = false

  private val bgTick =
    object : Runnable {
      override fun run() {
        try {
          maybeSpawnHeadless()
        } catch (e: Throwable) {
          Log.w(TAG, "bgTick failed", e)
        }
        bgHandler.postDelayed(this, BG_TICK_MS)
      }
    }

  private fun startBgTicks() {
    if (bgTickScheduled) return
    bgTickScheduled = true
    bgHandler.postDelayed(bgTick, BG_TICK_FIRST_MS)
  }

  private fun stopBgTicks() {
    bgHandler.removeCallbacks(bgTick)
    bgTickScheduled = false
  }

  private fun maybeSpawnHeadless() {
    // Kill-switch + local crash-loop breaker (fail-closed; read with THIS Service
    // Context — appContext is dead post-kill).
    if (!KaataBgMeshGate.isEnabled(this)) return
    // Single-mesh: never spawn while a foreground JS mesh is alive (it owns the
    // radio + DB). The cross-VM heartbeat is the only reliable cross-context
    // signal (AppState is per-VM).
    if (KaataBgMeshGate.isForegroundAlive(this, System.currentTimeMillis())) return

    // CUTOVER (flag DEFAULT OFF): when enabled, run the NATIVE MeshEngine in THIS
    // process (resident JVM, Briar-model) — no JS VM, so it isn't subject to the
    // headless-JS fragility and works on hostile OEMs too. Flag off => the legacy
    // headless-JS path below, unchanged (still gated off on MIUI).
    if (KaataBgMeshGate.isNativeEngineEnabled(this)) {
      spawnNativeEngineWindow()
      return
    }

    // MIUI/Xiaomi already 5s-crashed this app's headless path once; default to
    // Phase-1-only (expo-background-task) there until it's proven on-device.
    if (isHostileOem()) return
    try {
      startService(Intent(this, KaataMeshHeadlessService::class.java))
    } catch (e: Throwable) {
      // Background-start can be blocked on some OEMs — never let it crash the FGS.
      Log.w(TAG, "spawn headless window failed", e)
    }
  }

  @Volatile private var nativeEngineRunning = false

  /** Run one bounded native MeshEngine window on a daemon thread (Briar-model:
   *  in-process JVM accept/dial loops). Deduped so a tick can't overlap windows;
   *  wrapped so a failure can never crash the FGS. */
  private fun spawnNativeEngineWindow() {
    if (nativeEngineRunning) return
    nativeEngineRunning = true
    Thread({
      try {
        MeshEngine.runWindow(applicationContext, NATIVE_WINDOW_MS)
      } catch (e: Throwable) {
        Log.w(TAG, "native engine window failed", e)
      } finally {
        nativeEngineRunning = false
      }
    }, "kaata-mesh-engine").apply { isDaemon = true }.start()
  }

  private fun isHostileOem(): Boolean {
    val m = (Build.MANUFACTURER ?: "").lowercase()
    return m.contains("xiaomi") || m.contains("redmi") || m.contains("poco")
  }

  override fun onBind(intent: Intent?): IBinder? = null

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    val prefs = getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    if (intent?.action == ACTION_STOP) {
      // User turned Nearby sync off — clear the run-state + cancel the revival
      // alarm so we stay down (and don't get revived). Satisfy the 5s rule
      // defensively even on a stop command, then tear down.
      prefs.edit().putBoolean(KEY_FGS_SHOULD_RUN, false).apply()
      cancelRevivalAlarm(this)
      startForegroundSafely(buildNotification(prefs, intent))
      stopBgTicks()
      releaseWakeLock()
      stopForegroundCompat()
      stopSelf()
      return START_NOT_STICKY
    }

    // START / UPDATE / sticky-restart(null). Persist the latest copy so a
    // sticky restart (null intent, no JS yet) can rebuild the notification.
    if (intent != null) {
      val edit = prefs.edit()
      intent.getStringExtra(EXTRA_TITLE)?.let { edit.putString(KEY_TITLE, it) }
      intent.getStringExtra(EXTRA_BODY)?.let { edit.putString(KEY_BODY, it) }
      intent.getStringExtra(EXTRA_CHANNEL_NAME)?.let { edit.putString(KEY_CHANNEL_NAME, it) }
      intent.getStringExtra(EXTRA_CHANNEL_DESC)?.let { edit.putString(KEY_CHANNEL_DESC, it) }
      edit.apply()
    }

    val entered = startForegroundSafely(buildNotification(prefs, intent))
    if (!entered) {
      // Couldn't enter the foreground — e.g. an OS-initiated restart that landed
      // in an API 31+ background-start block, or a transient channel failure.
      // Do NOT return START_STICKY here: that would loop a never-foregrounded
      // service the OS keeps re-killing. Stop cleanly; MeshController's JS
      // auto-resume restarts us properly next time the app is foregrounded.
      releaseWakeLock()
      stopSelf()
      return START_NOT_STICKY
    }

    // In the foreground now — hold the partial wakelock so Doze can't freeze the
    // mesh and the process is a harder kill target (Briar's wakeLockManager).
    acquireWakeLock()

    // #43 P2: begin spawning bounded headless mesh windows so a swipe-killed phone
    // keeps syncing. Self-gated (kill-switch + heartbeat + OEM) so it's dark by
    // default and never spawns while a foreground JS mesh is alive.
    startBgTicks()

    // Record run-state + arm the Doze-exempt revival alarm (Briar parity P1b).
    // The alarm is the backstop for a HARD process kill the FGS+renewable-wakelock
    // couldn't prevent; the receiver gates actual revival on the bg-mesh switch.
    prefs.edit().putBoolean(KEY_FGS_SHOULD_RUN, true).apply()
    scheduleRevivalAlarm(this)

    // START_STICKY: if the OS kills us under memory pressure, recreate the
    // service (null intent) and we re-post the notification from prefs. The
    // mesh itself resumes in JS via MeshController's auto-resume when the user
    // next foregrounds the app (kaata's mesh runs in JS, not native).
    return START_STICKY
  }

  override fun onDestroy() {
    stopBgTicks()
    releaseWakeLock()
    stopForegroundCompat()
    super.onDestroy()
  }

  /** Returns true iff the service successfully entered the foreground. */
  private fun startForegroundSafely(notification: Notification): Boolean {
    return try {
      // connectedDevice ONLY (matches the manifest declaration), like Briar.
      // We deliberately do NOT use dataSync: on Android 14+ a dataSync FGS is
      // capped at ~6h/day and auto-stopped, which would silently kill always-on
      // sync. connectedDevice (we hold RFCOMM links to nearby phones) is not
      // time-limited.
      val type = ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE
      ServiceCompat.startForeground(this, NOTIF_ID, notification, type)
      true
    } catch (e: Throwable) {
      // Never let startForeground throw out of onStartCommand (it can throw
      // ForegroundServiceStartNotAllowedException synchronously on API 31+).
      // The caller decides whether to stop; see onStartCommand.
      Log.w(TAG, "startForeground failed", e)
      false
    }
  }

  private fun stopForegroundCompat() {
    try {
      ServiceCompat.stopForeground(this, ServiceCompat.STOP_FOREGROUND_REMOVE)
    } catch (e: Throwable) {
      Log.w(TAG, "stopForeground failed", e)
    }
  }

  private fun buildNotification(prefs: SharedPreferences, intent: Intent?): Notification {
    ensureChannel(prefs)

    val title =
      intent?.getStringExtra(EXTRA_TITLE) ?: prefs.getString(KEY_TITLE, null) ?: DEFAULT_TITLE
    val body =
      intent?.getStringExtra(EXTRA_BODY) ?: prefs.getString(KEY_BODY, null) ?: DEFAULT_BODY

    val launch = packageManager.getLaunchIntentForPackage(packageName)?.apply {
      addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
    }
    val contentPi: PendingIntent? =
      if (launch != null) {
        var flags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          flags = flags or PendingIntent.FLAG_IMMUTABLE
        }
        PendingIntent.getActivity(this, 0, launch, flags)
      } else {
        null
      }

    val builder = NotificationCompat.Builder(this, CHANNEL_ID)
      .setContentTitle(title)
      .setContentText(body)
      .setSmallIcon(resolveSmallIcon())
      .setOngoing(true)
      .setPriority(NotificationCompat.PRIORITY_LOW)
      .setVisibility(NotificationCompat.VISIBILITY_SECRET)
      .setShowWhen(false)
    if (contentPi != null) builder.setContentIntent(contentPi)
    return builder.build()
  }

  private fun ensureChannel(prefs: SharedPreferences) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
    val nm = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    // Don't clobber an existing channel — its name/description may already have
    // been set (localized) by the JS layer, and importance is user-controlled
    // after creation anyway.
    if (nm.getNotificationChannel(CHANNEL_ID) != null) return
    val name = prefs.getString(KEY_CHANNEL_NAME, null) ?: DEFAULT_CHANNEL_NAME
    val desc = prefs.getString(KEY_CHANNEL_DESC, null) ?: ""
    val channel = NotificationChannel(CHANNEL_ID, name, NotificationManager.IMPORTANCE_LOW).apply {
      description = desc
      enableVibration(false)
      setSound(null, null)
    }
    nm.createNotificationChannel(channel)
  }

  private fun resolveSmallIcon(): Int {
    // expo-notifications generates res/drawable*/notification_icon (see app.json).
    val id = resources.getIdentifier("notification_icon", "drawable", packageName)
    if (id != 0) return id
    // Fallbacks so startForeground never receives a 0 icon (which crashes).
    val appIcon = applicationInfo.icon
    if (appIcon != 0) return appIcon
    return android.R.drawable.ic_dialog_info
  }
}
