package expo.modules.kaatabtclassic.mesh

import org.json.JSONArray
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Test

/**
 * Crown-jewel parity: the Kotlin membership-chain fold (MeshTrust) must reach the
 * IDENTICAL verdict as the real lib/trust/chain.ts on a signed scenario.
 * Vectors generated by scripts/gen-trust-vectors.ts (runs the actual JS fold
 * under bun). A divergence here = wrong events accepted/rejected = data
 * corruption or sync failure, so this must be green before cutover.
 *
 * Scenario: genesis owner self-admit (anchor) -> add editor member (owner-signed)
 * -> add editor device (owner-signed) -> attacker member_added signed by a
 * non-owner key (must be refused).
 */
class MeshTrustParityTest {

  private val anchorPub = "25lf4lFp0UHKubu6krqgH58uHs599MsqwFGQ83/MH50="
  private val editorPub = "Y1VpHBeKj/kQB6dHivuVXvc1LGPnslcDmEz3iybiGlY="
  private val attackerPub = "My6+jSfLcyOzpAHBwTtd1kvMwOEOzaHCtdEaA3eaheU="
  private val vault = "vault-t"

  private val wireEventsJson =
    """
    [{"event_id":"evt-1","event_type":"vault_member_added","vault_id":"vault-t","target_id":"acct-owner","relationship_id":null,"hlc":{"pms":1000,"l":0,"did":"owner-dev"},"device_id":"owner-dev","author_seq":1,"actor_account_id":null,"payload":{"account_id":"acct-owner","role":"owner"},"schema_version":1,"event_sig_b64":"dNahljb6xWFbbTySa5eS5qADV/FE4PB9VH4tG7bQTug0LoiXReeISOGZkKtniVpgXnIWjKc5IngAHzaltRxhDA==","signer_device_pubkey":"25lf4lFp0UHKubu6krqgH58uHs599MsqwFGQ83/MH50="},{"event_id":"evt-2","event_type":"vault_member_added","vault_id":"vault-t","target_id":"acct-editor","relationship_id":null,"hlc":{"pms":1001,"l":0,"did":"owner-dev"},"device_id":"owner-dev","author_seq":1,"actor_account_id":null,"payload":{"account_id":"acct-editor","role":"editor"},"schema_version":1,"event_sig_b64":"WCaul6VkHzFwkvReeo8J+xw7I/P/nvJCklJgcbxE+a/3FOsaWeP0qVzIXRyoOHE3GXgDMUMaU7EmfXHiF10ZCQ==","signer_device_pubkey":"25lf4lFp0UHKubu6krqgH58uHs599MsqwFGQ83/MH50="},{"event_id":"evt-3","event_type":"vault_device_added","vault_id":"vault-t","target_id":"editor-dev","relationship_id":null,"hlc":{"pms":1002,"l":0,"did":"owner-dev"},"device_id":"owner-dev","author_seq":1,"actor_account_id":null,"payload":{"account_id":"acct-editor","device_id":"editor-dev","device_pubkey":"Y1VpHBeKj/kQB6dHivuVXvc1LGPnslcDmEz3iybiGlY="},"schema_version":1,"event_sig_b64":"vwl3oTcrhGITsGVjLqlVwBKq/qwCGf5UPy0J/8n3CbiAdRgsZAMz+ATSNqMrEHU3+F559LmOmtJgY9MvDAEMCw==","signer_device_pubkey":"25lf4lFp0UHKubu6krqgH58uHs599MsqwFGQ83/MH50="},{"event_id":"evt-4","event_type":"vault_member_added","vault_id":"vault-t","target_id":"acct-bad","relationship_id":null,"hlc":{"pms":1003,"l":0,"did":"bad-dev"},"device_id":"bad-dev","author_seq":1,"actor_account_id":null,"payload":{"account_id":"acct-bad","role":"editor"},"schema_version":1,"event_sig_b64":"O4GfV4ZfDYHQYGDb9NMWACFFzkY9tk4aWE4mtFt+Ifhco/TMANHwwhHREczGvth7jUZMlLB0h3BJX5ZcyNgZBA==","signer_device_pubkey":"My6+jSfLcyOzpAHBwTtd1kvMwOEOzaHCtdEaA3eaheU="}]
    """.trimIndent()

  private fun events(): List<MeshEvent> {
    val arr = JSONArray(wireEventsJson)
    return (0 until arr.length()).map { MeshEvent.fromWire(arr.getJSONObject(it)) }
  }

  @Test
  fun fold_matches_js() {
    val state = MeshTrust.foldMembership(vault, anchorPub, emptyList(), events())

    assertEquals(true, state.hasGenesis)

    // members: acct-owner(owner) + acct-editor(editor), acct-bad refused.
    assertEquals(2, state.members.size)
    assertEquals("owner", state.members["acct-owner"]!!.role)
    assertFalse(state.members["acct-owner"]!!.removed)
    assertEquals("editor", state.members["acct-editor"]!!.role)
    assertFalse(state.members["acct-editor"]!!.removed)

    // devices: anchor + editor bound.
    assertEquals(2, state.devices.size)
    assertEquals("owner-dev", state.devices[anchorPub]!!.deviceId)
    assertEquals("acct-owner", state.devices[anchorPub]!!.accountId)
    assertNotNull(state.devices[editorPub])
    assertEquals("acct-editor", state.devices[editorPub]!!.accountId)
    assertFalse(state.devices[editorPub]!!.removed)

    // attacker event refused with the exact JS reason.
    assertEquals(1, state.conflicts.size)
    assertEquals("evt-4", state.conflicts[0].eventId)
    assertEquals("signer_not_owner_device", state.conflicts[0].reason)
  }

  @Test
  fun verify_peer_proof_matches_js() {
    val ev = events()
    val ok = MeshTrust.verifyPeerProof(vault, anchorPub, emptyList(), ev, emptyList(), editorPub)
    assertEquals(MeshTrust.ProofVerdict.Ok("acct-editor", "editor", "editor-dev"), ok)

    val bad = MeshTrust.verifyPeerProof(vault, anchorPub, emptyList(), ev, emptyList(), attackerPub)
    assertEquals(MeshTrust.ProofVerdict.Fail("device_not_bound"), bad)
  }
}
