package expo.modules.kaatabtclassic.mesh

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-language parity: the native (Kotlin) mesh crypto + canonicalization must
 * reproduce the JS reference byte-for-byte, or remote events never verify and
 * background sync silently does nothing. Vectors are generated by
 * scripts/gen-mesh-vectors.mjs from the EXACT @noble libs the app ships — paste
 * its output here when the protocol changes. This is the gate that must be green
 * before the native engine is cut over.
 */
class MeshCryptoParityTest {

  private fun hex(s: String): ByteArray {
    val out = ByteArray(s.length / 2)
    for (i in out.indices) {
      out[i] = ((Character.digit(s[i * 2], 16) shl 4) or Character.digit(s[i * 2 + 1], 16)).toByte()
    }
    return out
  }

  private fun toHex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

  // ---- vectors from scripts/gen-mesh-vectors.mjs ----
  private val edSeed = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
  private val edPubB64 = "A6EHv/POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg="
  private val edMsg = "kaata mesh parity test"
  private val edSigB64 =
    "AnnOqOCMYIT9nxLaqPj4LyX7gxGbODKk6YxkBRwljKAAfx8ZXUvgKAh8+uU5UxVfeN+Jv+61cWdM6/f812kSAw=="

  private val xPrivA = "1111111111111111111111111111111111111111111111111111111111111111"
  private val xPrivB = "2222222222222222222222222222222222222222222222222222222222222222"
  private val xPubA = "7b4e909bbe7ffe44c465a220037d608ee35897d31ef972f07f74892cb0f73f13"
  private val xPubB = "0faa684ed28867b97f4a6a2dee5df8ce974e76b7018e3f22a1c4cf2678570f20"
  private val xShared = "9e004098efc091d4ec2663b4e9f5cfd4d7064571690b4bea97ab146ab9f35056"

  private val hkSalt = "parity-salt-1234"
  private val hkInfo = "kaata-mesh-aead-v2"
  private val hkOut = "f8c31f25b8815cb84f507943c4b0dbe5689721a0d7d3078ba97ef06c3e64d890"

  private val ccKey = "2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a"
  private val ccNonce = "000000010000000000000005"
  private val ccAad = "12340001000005"
  private val ccPt = "hello"
  private val ccCt = "3a210611694e47a287a501394bbd30137b4d7c36c8"

  private val canonicalHex =
    "7b226163746f725f6163636f756e745f6964223a6e756c6c2c226465766963655f6964223a226465762d31222c226576656e745f6964223a226576742d313233222c226576656e745f74797065223a22656e7472795f63726561746564222c22686c63223a7b22646964223a226465762d31222c226c223a372c22706d73223a313730303030303030303030307d2c227061796c6f6164223a7b22616d6f756e74223a343230302c226e616d65223a2241686d61642068c3a96c6c6f222c226e6573746564223a7b2278223a747275652c2279223a5b332c322c315d7d2c227a223a317d2c227061796c6f61645f736368656d61223a312c2272656c6174696f6e736869705f6964223a6e756c6c2c227461726765745f6964223a227467742d31222c227661756c745f6964223a227661756c742d616263227d"
  private val eventSigB64 =
    "lTxJB43VAaZJpRCl51eovKzsvwJKglRu7jLffcnqTTsiJdBA1K6jZ+jtbU/3oOJUfBHaDlE/H5S7n92BGwcbDg=="

  @Test
  fun ed25519_pubkey_and_sign_match_js() {
    val seed = hex(edSeed)
    assertEquals(edPubB64, MeshEventSig.b64StdEncode(MeshCrypto.ed25519PublicKeyFromSeed(seed)))
    val sig = MeshCrypto.ed25519Sign(edMsg.toByteArray(Charsets.UTF_8), seed)
    assertEquals(edSigB64, MeshEventSig.b64StdEncode(sig))
    assertTrue(
      MeshCrypto.ed25519Verify(
        MeshEventSig.b64StdDecode(edSigB64),
        edMsg.toByteArray(Charsets.UTF_8),
        MeshEventSig.b64StdDecode(edPubB64),
      )
    )
  }

  @Test
  fun x25519_pubkey_and_shared_secret_match_js() {
    assertEquals(xPubA, toHex(MeshCrypto.x25519PublicKey(hex(xPrivA))))
    assertEquals(xShared, toHex(MeshCrypto.x25519SharedSecret(hex(xPrivA), hex(xPubB))))
  }

  @Test
  fun hkdf_sha512_matches_js() {
    val out =
      MeshCrypto.hkdfSha512(
        hex(xShared),
        hkSalt.toByteArray(Charsets.UTF_8),
        hkInfo.toByteArray(Charsets.UTF_8),
        32,
      )
    assertEquals(hkOut, toHex(out))
  }

  @Test
  fun chacha20poly1305_matches_js_and_roundtrips() {
    val ct = MeshCrypto.chacha20poly1305Encrypt(hex(ccKey), hex(ccNonce), hex(ccAad), ccPt.toByteArray(Charsets.UTF_8))
    assertEquals(ccCt, toHex(ct))
    val pt = MeshCrypto.chacha20poly1305Decrypt(hex(ccKey), hex(ccNonce), hex(ccAad), ct)
    assertEquals(ccPt, String(pt, Charsets.UTF_8))
  }

  @Test
  fun canonicalize_event_matches_js() {
    // payload deliberately built with out-of-order / nested keys — canonicalize
    // must sort and reproduce the JS bytes exactly.
    val payload =
      JSONObject(
        "{\"z\":1,\"amount\":4200,\"name\":\"Ahmad héllo\",\"nested\":{\"y\":[3,2,1],\"x\":true}}"
      )
    val canon =
      MeshEventSig.canonicalizeEvent(
        eventId = "evt-123",
        eventType = "entry_created",
        vaultId = "vault-abc",
        targetId = "tgt-1",
        relationshipId = null,
        hlcDid = "dev-1",
        hlcL = 7L,
        hlcPms = 1700000000000L,
        deviceId = "dev-1",
        actorAccountId = null,
        payload = payload,
        payloadSchema = 1,
      )
    assertArrayEquals(hex(canonicalHex), canon)
    assertTrue(MeshEventSig.verifyEventSignature(canon, eventSigB64, edPubB64))
  }

  @Test
  fun planner_matches_js() {
    // computeContiguous (vectors from gen-mesh-vectors.mjs)
    val c1 = MeshPlanner.computeContiguous(listOf(1, 3, 5, 6))
    assertEquals(1, c1.frontier)
    assertEquals(listOf(2 to 2, 4 to 4), c1.gaps.map { it.fromSeq to it.toSeq })

    val c2 = MeshPlanner.computeContiguous(listOf(2, 3))
    assertEquals(0, c2.frontier)
    assertEquals(listOf(1 to 1), c2.gaps.map { it.fromSeq to it.toSeq })

    val c3 = MeshPlanner.computeContiguous(listOf(3, 1, 2, 2))
    assertEquals(3, c3.frontier)
    assertEquals(emptyList<Pair<Int, Int>>(), c3.gaps.map { it.fromSeq to it.toSeq })

    // planRangesToSend
    val ranges = MeshPlanner.planRangesToSend(mapOf("a" to 5, "b" to 2), mapOf("a" to 3))
    assertEquals(
      listOf(Triple("a", 4, 5), Triple("b", 1, 2)),
      ranges.map { Triple(it.deviceId, it.fromSeq, it.toSeq) },
    )

    // splitIntoBatches
    val batches = MeshPlanner.splitIntoBatches(listOf(MeshPlanner.SeqRange("a", 1, 5)), 2)
    assertEquals(
      listOf(
        listOf(Triple("a", 1, 2)),
        listOf(Triple("a", 3, 4)),
        listOf(Triple("a", 5, 5)),
      ),
      batches.map { b -> b.map { Triple(it.deviceId, it.fromSeq, it.toSeq) } },
    )
  }
}
