// apps/mobile/lib/mesh/transport.ts
//
// Phase 5.1 mesh transport: real react-native-webrtc data channel with a
// tiny in-process HTTP signaling server for SDP + ICE candidate exchange.
//
// ARCHITECTURE
// ------------
// Each peer runs an HTTP listener on an OS-assigned TCP port (advertised
// via mDNS by discovery.ts). The HTTP surface area is intentionally tiny:
//
//   POST /mesh/signal  body: { type: "offer" | "candidate" |
//                              "poll-candidates" | "close", sid, ... }
//
// A `sid` (session id) is generated by the dialer per attempt and routes
// every signal in that session to the same RTCPeerConnection on the
// answerer side. There is no auth on /mesh/signal: any LAN peer can dial
// us, and that's fine — the VMC handshake on the data channel
// (anti-entropy.ts) is the authentication layer, and DTLS encrypts the
// data channel.
//
// MESSAGE FRAMING
// ---------------
// WebRTC data channels are message-oriented but enforce a per-message
// size limit (~16 KB safely; some implementations cap at 64 KB). Mesh
// anti-entropy can ship JSON batches well beyond that. We frame every
// logical JSON message as:
//
//   <4-byte big-endian length><utf-8 payload bytes...>
//
// then split the framed bytes into <=16 KB chunks. The receiver
// reassembles by reading the length prefix from the first chunk and
// concatenating until it has `length` bytes of payload.
//
// TIMEOUTS
// --------
//   SDP_EXCHANGE_TIMEOUT_MS : 10s — POST offer -> receive answer
//   ICE_GATHERING_TIMEOUT_MS: 20s — local ICE candidate gathering
//   DC_OPEN_TIMEOUT_MS      : 30s — from RTCPeerConnection.new to dc.open
//
// RECONNECT
// ---------
// dialPeerWithRetry wraps dialPeer with 3 retries (1s, 2s, 4s backoff).
// After 3 failures the next discovery cycle re-dials.

import * as Crypto from "expo-crypto";
import { MeshTransportError } from "./errors";
import {
  startSignalingServer,
  type SignalingServerHandle,
  type SignalingSession,
} from "./signaling-server";

// ---------------------------------------------------------------------------
// Conditional native-module import. On web / Expo Go (no native binding),
// any property access lazily throws, but startTransportListener +
// dialPeer guard with an isWebRtcAvailable() check so callers get a
// clean MeshTransportError instead of an opaque "undefined is not an
// object" runtime crash.
// ---------------------------------------------------------------------------

type RTCPeerConnectionT = any;
type RTCDataChannelT = any;
type RTCIceCandidateInitT = any;

let webrtc: {
  RTCPeerConnection: new (config: any) => RTCPeerConnectionT;
  RTCIceCandidate: new (init: RTCIceCandidateInitT) => any;
  RTCSessionDescription: new (init: { type: string; sdp: string }) => any;
} | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  webrtc = require("react-native-webrtc");
} catch {
  webrtc = null;
}

function isWebRtcAvailable(): boolean {
  return !!webrtc && typeof webrtc.RTCPeerConnection === "function";
}

// ---------------------------------------------------------------------------
// Public interface
// ---------------------------------------------------------------------------

// Phase 6: MeshConnection interface moved to transport-interface.ts so the
// BLE transport (transport-ble.ts) can implement the same contract without
// importing this WebRTC-specific module. Re-exported here so existing
// callers `import { MeshConnection } from "./transport"` keep working.
export type { MeshConnection } from "./transport-interface";
import type { MeshConnection } from "./transport-interface";

export type PeerHint = {
  host: string;
  port: number;
  serviceName?: string;
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const SDP_EXCHANGE_TIMEOUT_MS = 10_000;
const ICE_GATHERING_TIMEOUT_MS = 20_000;
const DC_OPEN_TIMEOUT_MS = 30_000;
const MAX_CHUNK_BYTES = 16 * 1024; // safe SCTP message size
// Receiver-side sanity cap: refuse to allocate a reassembly buffer larger
// than this. A malicious or buggy peer could otherwise send a 4-byte
// big-endian length of 0xFFFFFFFF (~4GB) and we'd OOM trying to allocate.
// 16 MB is well above any legitimate anti-entropy batch (capped at <1MB
// in practice) and is safely below RN's per-allocation ceiling.
const MAX_FRAME_BYTES = 16 * 1024 * 1024;
const DATA_CHANNEL_LABEL = "kaata";

const WEBRTC_CONFIG = {
  iceServers: [] as any[], // local-only, no STUN/TURN
  iceTransportPolicy: "all",
  bundlePolicy: "max-bundle",
};

// ---------------------------------------------------------------------------
// Listener
// ---------------------------------------------------------------------------

let serverHandle: SignalingServerHandle | null = null;
let activeIncomingHandler: ((conn: MeshConnection) => void) | null = null;

export async function startTransportListener(opts: {
  onIncomingConnection: (conn: MeshConnection) => void;
}): Promise<{ port: number }> {
  if (serverHandle) {
    return { port: serverHandle.port };
  }
  if (!isWebRtcAvailable()) {
    // Mesh is gated by shop_mode_enabled which can only be true in a dev
    // client build; this branch is reached in Expo Go / web / simulator
    // without the native binding. Return port 0 so discovery advertises
    // nothing and peers skip us cleanly.
    return { port: 0 };
  }
  activeIncomingHandler = opts.onIncomingConnection;
  try {
    serverHandle = await startSignalingServer({
      onOffer: handleIncomingOffer,
    });
  } catch (err) {
    if (err instanceof MeshTransportError && err.code === "not_implemented") {
      // No TCP-socket native module either — soft-fail.
      return { port: 0 };
    }
    throw err;
  }
  return { port: serverHandle.port };
}

export async function stopTransportListener(): Promise<void> {
  if (serverHandle) {
    await serverHandle.stop();
    serverHandle = null;
  }
  activeIncomingHandler = null;
}

// ---------------------------------------------------------------------------
// Incoming handshake
// ---------------------------------------------------------------------------

async function handleIncomingOffer(session: SignalingSession): Promise<void> {
  if (!isWebRtcAvailable() || !webrtc) {
    await session.fail("webrtc not available");
    return;
  }
  const handler = activeIncomingHandler;
  if (!handler) {
    await session.fail("listener not active");
    return;
  }

  const pc: RTCPeerConnectionT = new webrtc.RTCPeerConnection(WEBRTC_CONFIG);
  let dc: RTCDataChannelT | null = null;
  let conn: WebRtcMeshConnection | null = null;
  let dcOpenTimer: any = null;
  let settled = false;

  const cleanup = (err?: Error) => {
    if (settled) return;
    settled = true;
    if (dcOpenTimer) clearTimeout(dcOpenTimer);
    if (err) {
      try {
        pc.close();
      } catch {
        /* */
      }
    }
  };

  pc.addEventListener?.("icecandidate", (ev: any) => {
    // Trickle our local candidates to the dialer via the session's
    // poll endpoint.
    session.pushLocalCandidate(ev.candidate ?? null);
  });

  pc.addEventListener?.("datachannel", (ev: any) => {
    dc = ev.channel;
    if (!dc) return;
    conn = new WebRtcMeshConnection(pc, dc);
    conn.attachDataChannelHandlers(() => {
      cleanup();
      try {
        if (conn) handler(conn);
      } catch {
        /* swallow — caller is responsible for handshake errors */
      }
    });
  });

  // Apply the remote offer.
  try {
    await pc.setRemoteDescription(
      new webrtc.RTCSessionDescription({
        type: "offer",
        sdp: session.offerSdp,
      }),
    );
    const answer = await pc.createAnswer();
    await pc.setLocalDescription(answer);
    await session.sendAnswer(answer.sdp);
  } catch (e: any) {
    cleanup(e);
    await session.fail(`answer failed: ${e?.message ?? e}`);
    return;
  }

  // Pipe inbound remote ICE candidates into the peer connection as
  // they arrive on the signaling server.
  session.onRemoteCandidate(async (cand) => {
    try {
      if (cand && webrtc) {
        await pc.addIceCandidate(new webrtc.RTCIceCandidate(cand));
      }
    } catch {
      /* malformed candidate — ignore, ICE will recover or time out */
    }
  });

  // Watchdog: kill the half-open connection if the data channel never
  // opens within DC_OPEN_TIMEOUT_MS. Also notify the session so the dialer
  // can give up its candidate-polling loop early — otherwise it would keep
  // POSTing /poll-candidates for the full ICE_GATHERING_TIMEOUT_MS window.
  dcOpenTimer = setTimeout(() => {
    if (!conn || !conn.isOpen()) {
      cleanup(new Error("data channel open timeout"));
      session.fail("dc open timeout").catch(() => {
        /* best-effort */
      });
    }
  }, DC_OPEN_TIMEOUT_MS);
}

// ---------------------------------------------------------------------------
// Outbound dial
// ---------------------------------------------------------------------------

export async function dialPeer(peer: PeerHint): Promise<MeshConnection> {
  if (!isWebRtcAvailable() || !webrtc) {
    throw new MeshTransportError(
      "react-native-webrtc native module not available; mesh requires a dev/preview build",
      "not_implemented",
    );
  }

  const sid = randomSid();
  const pc: RTCPeerConnectionT = new webrtc.RTCPeerConnection(WEBRTC_CONFIG);
  // Dialer creates the data channel; answerer receives via ondatachannel.
  const dc: RTCDataChannelT = pc.createDataChannel(DATA_CHANNEL_LABEL, {
    ordered: true,
    // omit maxRetransmits → reliable (default)
  });

  const conn = new WebRtcMeshConnection(pc, dc);
  let dcOpenTimer: any = null;
  let candidateTrickleStop: (() => void) | null = null;

  const fail = async (msg: string, code?: string): Promise<never> => {
    if (dcOpenTimer) clearTimeout(dcOpenTimer);
    if (candidateTrickleStop) candidateTrickleStop();
    try {
      await postSignal(peer, { type: "close", sid });
    } catch {
      /* */
    }
    try {
      pc.close();
    } catch {
      /* */
    }
    throw new MeshTransportError(msg, code);
  };

  // Local ICE candidates → POST to peer as they're gathered.
  pc.addEventListener?.("icecandidate", (ev: any) => {
    const cand = ev.candidate ?? null;
    // Fire-and-forget; errors here aren't fatal — peer may still gather
    // enough host candidates from its own setRemoteDescription pass.
    postSignal(peer, { type: "candidate", sid, candidate: cand }).catch(() => {
      /* */
    });
  });

  // Create + send offer.
  let answerSdp: string;
  try {
    const offer: any = await withTimeout<any>(
      pc.createOffer({}),
      SDP_EXCHANGE_TIMEOUT_MS,
      "createOffer timeout",
    );
    await pc.setLocalDescription(offer);
    const answerRes: any = await withTimeout<any>(
      postSignal(peer, { type: "offer", sid, sdp: offer.sdp }),
      SDP_EXCHANGE_TIMEOUT_MS,
      "signaling: offer/answer exchange timeout",
    );
    if (!answerRes || answerRes.type !== "answer" || typeof answerRes.sdp !== "string") {
      return await fail("signaling: malformed answer", "signaling_malformed");
    }
    answerSdp = answerRes.sdp;
    await pc.setRemoteDescription(
      new webrtc.RTCSessionDescription({ type: "answer", sdp: answerSdp }),
    );
  } catch (e: any) {
    return await fail(`signaling failed: ${e?.message ?? e}`, "signaling_connect_failed");
  }

  // Poll for the peer's ICE candidates (they post-back via /mesh/signal
  // candidate messages while we're polling). The poll is a passive
  // long-ish poll; we stop it as soon as the data channel is open or
  // ICE_GATHERING_TIMEOUT_MS elapses.
  candidateTrickleStop = startCandidatePolling(peer, sid, pc, ICE_GATHERING_TIMEOUT_MS);

  // Wait for the data channel to open.
  try {
    await new Promise<void>((resolve, reject) => {
      dcOpenTimer = setTimeout(() => {
        reject(
          new MeshTransportError(
            `data channel did not open within ${DC_OPEN_TIMEOUT_MS}ms`,
            "channel_open_timeout",
          ),
        );
      }, DC_OPEN_TIMEOUT_MS);
      conn.attachDataChannelHandlers(() => {
        if (dcOpenTimer) clearTimeout(dcOpenTimer);
        resolve();
      });
    });
  } catch (e: any) {
    return await fail(e?.message ?? "channel open failed", "channel_open_timeout");
  }

  if (candidateTrickleStop) candidateTrickleStop();
  return conn;
}

// ---------------------------------------------------------------------------
// Retry wrapper for the scheduler
// ---------------------------------------------------------------------------

/**
 * dialPeerWithRetry — attempts dialPeer up to (1 + 3) times with 1s/2s/4s
 * backoff. The next discovery cycle handles re-dialing after a full
 * give-up.
 */
export async function dialPeerWithRetry(peer: PeerHint): Promise<MeshConnection> {
  const backoffsMs = [0, 1000, 2000, 4000]; // first attempt + 3 retries
  let lastErr: unknown = null;
  for (let i = 0; i < backoffsMs.length; i++) {
    const wait = backoffsMs[i];
    if (wait > 0) await sleep(wait);
    try {
      return await dialPeer(peer);
    } catch (e) {
      lastErr = e;
      // Don't retry "not_implemented" — the runtime can't satisfy it.
      if (e instanceof MeshTransportError && e.code === "not_implemented") {
        throw e;
      }
    }
  }
  throw lastErr instanceof Error
    ? lastErr
    : new MeshTransportError("dialPeer failed after retries", "retries_exhausted");
}

// ---------------------------------------------------------------------------
// Candidate polling (dialer side)
// ---------------------------------------------------------------------------

function startCandidatePolling(
  peer: PeerHint,
  sid: string,
  pc: RTCPeerConnectionT,
  budgetMs: number,
): () => void {
  let stopped = false;
  const deadline = Date.now() + budgetMs;

  const loop = async () => {
    while (!stopped && Date.now() < deadline) {
      try {
        const res: any = await postSignal(peer, {
          type: "poll-candidates",
          sid,
        });
        if (res && Array.isArray(res.candidates)) {
          for (const c of res.candidates) {
            if (stopped) return;
            try {
              if (c && webrtc) {
                await pc.addIceCandidate(new webrtc.RTCIceCandidate(c));
              }
            } catch {
              /* malformed candidate — ignore */
            }
          }
        }
        if (res?.done) return;
      } catch {
        // Network blip — back off then keep going until budget elapses.
      }
      await sleep(500);
    }
  };
  void loop();
  return () => {
    stopped = true;
  };
}

// ---------------------------------------------------------------------------
// HTTP signal POST (used by both sides)
// ---------------------------------------------------------------------------

async function postSignal(peer: PeerHint, body: any): Promise<any | null> {
  const url = `http://${peer.host}:${peer.port}/mesh/signal`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (res.status === 204) return null;
  if (!res.ok) {
    throw new MeshTransportError(
      `signaling POST ${url} failed: ${res.status}`,
      "signaling_http_error",
    );
  }
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch (e: any) {
    throw new MeshTransportError(`signaling JSON parse: ${e?.message ?? e}`, "signaling_malformed");
  }
}

// ---------------------------------------------------------------------------
// WebRTC-backed MeshConnection
// ---------------------------------------------------------------------------

class WebRtcMeshConnection implements MeshConnection {
  readonly kind = "webrtc" as const;
  remoteDeviceId: string | null = null;
  private pc: RTCPeerConnectionT;
  private dc: RTCDataChannelT;
  private inbox: unknown[] = [];
  private resolvers: ((v: unknown) => void)[] = [];
  private closed = false;
  private reassemblyBuf: Uint8Array | null = null;
  private reassemblyExpected = 0;

  constructor(pc: RTCPeerConnectionT, dc: RTCDataChannelT) {
    this.pc = pc;
    this.dc = dc;
    // react-native-webrtc data channels deliver bytes as ArrayBuffer or
    // string depending on send() input; we want binary throughout.
    try {
      this.dc.binaryType = "arraybuffer";
    } catch {
      /* */
    }
  }

  isOpen(): boolean {
    return !this.closed && this.dc?.readyState === "open";
  }

  attachDataChannelHandlers(onOpen: () => void): void {
    const dc = this.dc;
    const finishOpen = () => {
      if (dc.readyState === "open") onOpen();
    };
    // Some implementations fire "open" via addEventListener, others via
    // the on* property setter. Cover both.
    dc.addEventListener?.("open", finishOpen);
    dc.onopen = finishOpen;
    if (dc.readyState === "open") {
      // Race: channel opened before we attached.
      onOpen();
    }
    const onMsg = (ev: any) => this.onMessage(ev?.data);
    dc.addEventListener?.("message", onMsg);
    dc.onmessage = onMsg;

    const onClose = () => this.markClosed();
    dc.addEventListener?.("close", onClose);
    dc.onclose = onClose;

    const onErr = () => this.markClosed();
    dc.addEventListener?.("error", onErr);
    dc.onerror = onErr;
  }

  private onMessage(raw: any): void {
    if (raw == null) return;
    const bytes = toUint8(raw);
    if (!bytes) return;

    // Accumulate framed bytes; emit one JSON message per complete frame.
    let cursor = 0;
    while (cursor < bytes.length) {
      if (!this.reassemblyBuf) {
        // Beginning of a new frame: read 4-byte length.
        if (bytes.length - cursor < 4) {
          // Partial header at chunk boundary; stash and wait for more.
          this.reassemblyBuf = bytes.slice(cursor);
          this.reassemblyExpected = -1; // sentinel: header not yet complete
          return;
        }
        const len =
          (bytes[cursor] << 24) |
          (bytes[cursor + 1] << 16) |
          (bytes[cursor + 2] << 8) |
          bytes[cursor + 3];
        cursor += 4;
        const lenU = len >>> 0;
        if (lenU > MAX_FRAME_BYTES) {
          // OOM defense — refuse oversized frames, drop the connection.
          // The remote is either buggy or hostile; either way we don't
          // want to allocate up to 4GB to find out.
          this.reassemblyBuf = null;
          this.reassemblyExpected = 0;
          this.markClosed();
          try {
            this.dc?.close?.();
          } catch {
            /* */
          }
          try {
            this.pc?.close?.();
          } catch {
            /* */
          }
          return;
        }
        this.reassemblyExpected = lenU;
        this.reassemblyBuf = new Uint8Array(0);
      } else if (this.reassemblyExpected === -1) {
        // Complete a partial header.
        const stash = this.reassemblyBuf;
        const need = 4 - stash.length;
        if (bytes.length - cursor < need) {
          const merged = new Uint8Array(stash.length + (bytes.length - cursor));
          merged.set(stash, 0);
          merged.set(bytes.slice(cursor), stash.length);
          this.reassemblyBuf = merged;
          return;
        }
        const merged = new Uint8Array(4);
        merged.set(stash, 0);
        merged.set(bytes.slice(cursor, cursor + need), stash.length);
        cursor += need;
        const len = (merged[0] << 24) | (merged[1] << 16) | (merged[2] << 8) | merged[3];
        const lenU = len >>> 0;
        if (lenU > MAX_FRAME_BYTES) {
          // Same OOM defense as the fast path above.
          this.reassemblyBuf = null;
          this.reassemblyExpected = 0;
          this.markClosed();
          try {
            this.dc?.close?.();
          } catch {
            /* */
          }
          try {
            this.pc?.close?.();
          } catch {
            /* */
          }
          return;
        }
        this.reassemblyExpected = lenU;
        this.reassemblyBuf = new Uint8Array(0);
      }

      // Append payload bytes.
      const remaining = this.reassemblyExpected - this.reassemblyBuf.length;
      const take = Math.min(remaining, bytes.length - cursor);
      if (take > 0) {
        const next = new Uint8Array(this.reassemblyBuf.length + take);
        next.set(this.reassemblyBuf, 0);
        next.set(bytes.slice(cursor, cursor + take), this.reassemblyBuf.length);
        this.reassemblyBuf = next;
        cursor += take;
      }

      if (this.reassemblyBuf.length === this.reassemblyExpected) {
        const payload = this.reassemblyBuf;
        this.reassemblyBuf = null;
        this.reassemblyExpected = 0;
        let parsed: unknown;
        try {
          parsed = JSON.parse(utf8Decode(payload));
        } catch {
          // Drop malformed frames silently; anti-entropy will time out.
          continue;
        }
        const r = this.resolvers.shift();
        if (r) r(parsed);
        else this.inbox.push(parsed);
      }
    }
  }

  private markClosed(): void {
    if (this.closed) return;
    this.closed = true;
    for (const r of this.resolvers) {
      try {
        r({ __closed: true });
      } catch {
        /* */
      }
    }
    this.resolvers = [];
  }

  async sendJSON(obj: unknown): Promise<void> {
    if (this.closed) throw new MeshTransportError("sendJSON on closed connection");
    if (this.dc.readyState !== "open") {
      throw new MeshTransportError(
        `sendJSON: data channel not open (state=${this.dc.readyState})`,
        "channel_not_open",
      );
    }
    const payload = utf8Encode(JSON.stringify(obj));
    const framed = new Uint8Array(4 + payload.length);
    framed[0] = (payload.length >>> 24) & 0xff;
    framed[1] = (payload.length >>> 16) & 0xff;
    framed[2] = (payload.length >>> 8) & 0xff;
    framed[3] = payload.length & 0xff;
    framed.set(payload, 4);

    // Chunk to MAX_CHUNK_BYTES.
    let offset = 0;
    while (offset < framed.length) {
      const end = Math.min(offset + MAX_CHUNK_BYTES, framed.length);
      const slice = framed.slice(offset, end);
      // react-native-webrtc accepts ArrayBuffer.
      this.dc.send(slice.buffer);
      offset = end;
      // Yield to the event loop so we don't monopolize on huge messages.
      if (offset < framed.length) await sleep(0);
    }
  }

  recvJSON(timeoutMs: number): Promise<unknown> {
    return new Promise((resolve, reject) => {
      if (this.closed) {
        resolve({ __closed: true });
        return;
      }
      const queued = this.inbox.shift();
      if (queued !== undefined) {
        resolve(queued);
        return;
      }
      const timer = setTimeout(() => {
        const i = this.resolvers.indexOf(r);
        if (i >= 0) this.resolvers.splice(i, 1);
        reject(new MeshTransportError(`recvJSON timed out after ${timeoutMs}ms`, "timeout"));
      }, timeoutMs);
      const r = (m: unknown) => {
        clearTimeout(timer);
        resolve(m);
      };
      this.resolvers.push(r);
    });
  }

  async close(): Promise<void> {
    this.markClosed();
    try {
      this.dc?.close?.();
    } catch {
      /* */
    }
    try {
      this.pc?.close?.();
    } catch {
      /* */
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function withTimeout<T>(p: Promise<T>, ms: number, msg: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new MeshTransportError(msg, "timeout")), ms);
    p.then(
      (v) => {
        clearTimeout(t);
        resolve(v);
      },
      (e) => {
        clearTimeout(t);
        reject(e);
      },
    );
  });
}

function randomSid(): string {
  // 16 hex chars (64 bits). Math.random() is predictable on Hermes, which
  // would let a malicious LAN peer guess in-flight sids and inject fake
  // `close` or `candidate` messages into our session. Use the platform
  // CSPRNG. Fall back to Math.random() only if expo-crypto is somehow
  // unavailable — that path is still SAFE in the sense that the worst case
  // is a session hijack which the VMC handshake on the data channel
  // still refuses; we just lose the defense-in-depth.
  try {
    const bytes = Crypto.getRandomBytes(8);
    let out = "";
    for (let i = 0; i < bytes.length; i++) {
      const b = bytes[i];
      out += (b >>> 4).toString(16) + (b & 0x0f).toString(16);
    }
    return out;
  } catch {
    const chars = "0123456789abcdef";
    let out = "";
    for (let i = 0; i < 16; i++) out += chars[Math.floor(Math.random() * 16)];
    return out;
  }
}

function toUint8(raw: any): Uint8Array | null {
  if (raw instanceof Uint8Array) return raw;
  if (raw instanceof ArrayBuffer) return new Uint8Array(raw);
  if (raw && typeof raw === "object" && "buffer" in raw && raw.buffer instanceof ArrayBuffer) {
    return new Uint8Array(raw.buffer, raw.byteOffset, raw.byteLength);
  }
  if (typeof raw === "string") return utf8Encode(raw);
  return null;
}

function utf8Encode(s: string): Uint8Array {
  // Use built-in TextEncoder; RN 0.81 ships with TextEncoder.
  return new TextEncoder().encode(s);
}

function utf8Decode(b: Uint8Array): string {
  return new TextDecoder("utf-8").decode(b);
}

// ---------------------------------------------------------------------------
// In-memory test/diagnostic pair (unchanged from Phase 5.0)
// ---------------------------------------------------------------------------

type Message = unknown;

class InMemoryConnection implements MeshConnection {
  readonly kind = "memory" as const;
  remoteDeviceId: string | null = null;
  private inbox: Message[] = [];
  private resolvers: ((m: Message) => void)[] = [];
  private closed = false;
  private peer: InMemoryConnection | null = null;

  setPeer(other: InMemoryConnection) {
    this.peer = other;
  }

  async sendJSON(obj: unknown): Promise<void> {
    if (this.closed) throw new MeshTransportError("sendJSON on closed connection");
    const peer = this.peer;
    if (!peer) throw new MeshTransportError("no peer attached");
    peer.deliver(obj);
  }

  deliver(m: Message): void {
    const r = this.resolvers.shift();
    if (r) r(m);
    else this.inbox.push(m);
  }

  recvJSON(timeoutMs: number): Promise<unknown> {
    return new Promise((resolve, reject) => {
      const queued = this.inbox.shift();
      if (queued !== undefined) {
        resolve(queued);
        return;
      }
      const timer = setTimeout(() => {
        const idx = this.resolvers.indexOf(r);
        if (idx >= 0) this.resolvers.splice(idx, 1);
        reject(new MeshTransportError(`recvJSON timed out after ${timeoutMs}ms`, "timeout"));
      }, timeoutMs);
      const r = (m: Message) => {
        clearTimeout(timer);
        resolve(m);
      };
      this.resolvers.push(r);
    });
  }

  async close(): Promise<void> {
    this.closed = true;
    for (const r of this.resolvers) {
      try {
        r({ __closed: true });
      } catch {
        /* */
      }
    }
    this.resolvers = [];
    if (this.peer && !this.peer.closed) this.peer.close();
  }
}

/** Test helper: create a back-to-back in-memory pair of MeshConnections. */
export function createInMemoryPair(): [MeshConnection, MeshConnection] {
  const a = new InMemoryConnection();
  const b = new InMemoryConnection();
  a.setPeer(b);
  b.setPeer(a);
  return [a, b];
}
