// apps/mobile/plugins/withBackupRules.js
//
// Expo config plugin: make Android Auto Backup + device-transfer actually include
// the shopkeeper's ledger (the SQLite database) — the single highest-stakes fix
// for a ledger app.
//
// THE BUG THIS FIXES (confirmed at source):
//   expo-secure-store ships backup rules (referenced by the merged manifest as
//   @xml/secure_store_backup_rules / @xml/secure_store_data_extraction_rules)
//   that read:
//       <include domain="sharedpref" path="."/>
//       <exclude domain="sharedpref" path="SecureStore"/>
//   Android's rule semantics: as soon as ANY <include> is present, ONLY the listed
//   domains are backed up. So `sharedpref` is backed up but the `file` domain —
//   where expo-sqlite stores kaata.db at filesDir/SQLite/ (SQLite.openDatabaseAsync
//   "kaata.db", lib/db-tx.ts) — is SILENTLY EXCLUDED. Result: a factory reset or a
//   new phone loses the ENTIRE ledger even for a user WITH a Google account and
//   backup enabled. No warning. For a debt book that is catastrophic.
//
// THE FIX:
//   Own the backup-rule resources ourselves. We write our own XML (a SUPERSET of
//   expo-secure-store's: still back up sharedprefs, still EXCLUDE the keystore-bound
//   SecureStore prefs — they can't be restored on another device — but ALSO include
//   the SQLite directory) and point the manifest at our files. App-module config
//   wins over the library default.
//
//   We back up the whole SQLite/ folder (kaata.db + -wal + -shm) so SQLite's
//   recovery sees a consistent set on restore. Auto Backup snapshots files while
//   the process is dead (Doze/charging/idle), so they're quiescent.
//
// Verify after prebuild:
//   grep fullBackupContent android/app/src/main/AndroidManifest.xml   # -> @xml/kaata_backup_rules
//   cat android/app/src/main/res/xml/kaata_backup_rules.xml
//   adb backup / reinstall test on a real Android 11 AND 12+ device.

const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const BACKUP_RULES_NAME = "kaata_backup_rules";
const DATA_EXTRACTION_RULES_NAME = "kaata_data_extraction_rules";

// Android < 12 (API <= 30): fullBackupContent.
const FULL_BACKUP_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js — do not edit by hand. -->
<full-backup-content>
    <include domain="sharedpref" path="."/>
    <exclude domain="sharedpref" path="SecureStore"/>
    <include domain="file" path="SQLite/"/>
</full-backup-content>
`;

// Android 12+ (API >= 31): dataExtractionRules. Same set for cloud-backup AND
// device-transfer so a phone-to-phone transfer also carries the ledger.
const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js — do not edit by hand. -->
<data-extraction-rules>
    <cloud-backup>
        <include domain="sharedpref" path="."/>
        <exclude domain="sharedpref" path="SecureStore"/>
        <include domain="file" path="SQLite/"/>
    </cloud-backup>
    <device-transfer>
        <include domain="sharedpref" path="."/>
        <exclude domain="sharedpref" path="SecureStore"/>
        <include domain="file" path="SQLite/"/>
    </device-transfer>
</data-extraction-rules>
`;

function withBackupRuleFiles(config) {
  return withDangerousMod(config, [
    "android",
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "xml",
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, `${BACKUP_RULES_NAME}.xml`), FULL_BACKUP_CONTENT);
      fs.writeFileSync(
        path.join(xmlDir, `${DATA_EXTRACTION_RULES_NAME}.xml`),
        DATA_EXTRACTION_RULES,
      );
      return cfg;
    },
  ]);
}

function withBackupManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults?.manifest?.application?.[0];
    if (!app?.$) return cfg;
    app.$["android:allowBackup"] = "true";
    app.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_NAME}`;
    app.$["android:dataExtractionRules"] = `@xml/${DATA_EXTRACTION_RULES_NAME}`;
    return cfg;
  });
}

module.exports = function withBackupRules(config) {
  return withBackupManifest(withBackupRuleFiles(config));
};
